/* The breed suggestions behind the profile modal's Breed field. It is a
   datalist, so anything typed is accepted; this only shapes the
   autocomplete. Popular Australian crosses sit alongside the pedigree
   breeds because that is what people type. */
window.ETHO_BREEDS = [
  'Affenpinscher', 'Afghan Hound', 'Airedale Terrier', 'Akita', 'Alaskan Malamute',
  'American Bulldog', 'American Staffordshire Terrier', 'Australian Cattle Dog',
  'Australian Kelpie', 'Australian Shepherd', 'Australian Silky Terrier',
  'Australian Terrier', 'Basenji', 'Basset Hound', 'Beagle', 'Bearded Collie',
  'Bedlington Terrier', 'Belgian Malinois', 'Belgian Shepherd', 'Bernese Mountain Dog',
  'Bichon Frise', 'Bloodhound', 'Border Collie', 'Border Terrier', 'Borzoi',
  'Boston Terrier', 'Bouvier des Flandres', 'Boxer', 'Briard', 'Brittany',
  'Bull Terrier', 'Bulldog', 'Bullmastiff', 'Cairn Terrier', 'Cane Corso',
  'Cavalier King Charles Spaniel', 'Cavoodle', 'Chihuahua', 'Chinese Crested',
  'Chow Chow', 'Cocker Spaniel', 'Collie', 'Coolie', 'Curly Coated Retriever',
  'Dachshund', 'Dalmatian', 'Dobermann', 'Dogue de Bordeaux', 'English Setter',
  'English Springer Spaniel', 'English Staffy', 'Field Spaniel', 'Finnish Lapphund',
  'Flat Coated Retriever', 'Fox Terrier', 'French Bulldog', 'German Shepherd',
  'German Shorthaired Pointer', 'German Spitz', 'German Wirehaired Pointer',
  'Giant Schnauzer', 'Golden Retriever', 'Gordon Setter', 'Great Dane',
  'Greater Swiss Mountain Dog', 'Greyhound', 'Groodle', 'Havanese',
  'Hungarian Vizsla', 'Irish Setter', 'Irish Terrier', 'Irish Wolfhound',
  'Italian Greyhound', 'Jack Russell Terrier', 'Japanese Chin', 'Japanese Spitz',
  'Keeshond', 'Kelpie cross', 'Kerry Blue Terrier', 'King Charles Spaniel',
  'Koolie', 'Labradoodle', 'Labrador Retriever', 'Lagotto Romagnolo',
  'Lakeland Terrier', 'Leonberger', 'Lhasa Apso', 'Lowchen', 'Maltese',
  'Maltese Shih Tzu', 'Manchester Terrier', 'Maremma Sheepdog', 'Mastiff',
  'Miniature Pinscher', 'Miniature Poodle', 'Miniature Schnauzer', 'Moodle',
  'Neapolitan Mastiff', 'Newfoundland', 'Norfolk Terrier', 'Norwegian Elkhound',
  'Norwich Terrier', 'Nova Scotia Duck Tolling Retriever', 'Old English Sheepdog',
  'Papillon', 'Pekingese', 'Pembroke Welsh Corgi', 'Pharaoh Hound', 'Pointer',
  'Pomeranian', 'Poodle', 'Portuguese Water Dog', 'Pug', 'Pugalier', 'Puggle',
  'Puli', 'Pyrenean Mountain Dog', 'Rhodesian Ridgeback', 'Rottweiler',
  'Rough Collie', 'Saint Bernard', 'Saluki', 'Samoyed', 'Schipperke',
  'Schnauzer', 'Schnoodle', 'Scottish Terrier', 'Sealyham Terrier', 'Shar Pei',
  'Shetland Sheepdog', 'Shiba Inu', 'Shih Tzu', 'Siberian Husky', 'Skye Terrier',
  'Smooth Collie', 'Soft Coated Wheaten Terrier', 'Spoodle', 'Staffordshire Bull Terrier',
  'Standard Poodle', 'Sussex Spaniel', 'Swedish Vallhund', 'Tenterfield Terrier',
  'Tibetan Spaniel', 'Tibetan Terrier', 'Toy Poodle', 'Weimaraner',
  'Welsh Springer Spaniel', 'Welsh Terrier', 'West Highland White Terrier',
  'Whippet', 'Wire Haired Fox Terrier', 'Yorkshire Terrier',
  'Rescue, breed unknown',
];
